CREATE TABLE IF NOT EXISTS `page_views` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `view_timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `page_url` VARCHAR(2048) NOT NULL,
  `ip_address` VARCHAR(45) NOT NULL
);
